# version: "3"

# services:
#   database:
#     build: ./database
#     ports:
#       - "3307:3306"
#     networks:
#       - springnet

#   backend:
#     build: ./backend
#     ports:
#       - "8080:8080"
#     networks:
#       - springnet
#     depends_on:
#       - database
# networks:
#   springnet:

version: "3"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: du_an_demo
      MYSQL_PASSWORD: 123456
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend_net
  backend:
    build:
      context: ./backend # Path to your Spring Boot application code
      dockerfile: Dockerfile # Dockerfile to build the Spring Boot app image
    container_name: spring-backend
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/du_an_demo
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_MAIL_HOST: smtp.gmail.com
      SPRING_MAIL_PORT: 587
      SPRING_MAIL_USERNAME: vuduc1611@gmail.com
      SPRING_MAIL_PASSWORD: qois efpx brso ioms
      SPRING_MAIL_PROPERTIES.mail.smtp.auth: true
      SPRING_MAIL_PROPERTIES.mail.smtp.starttls.enable: true
      FE_API_URL: http://localhost:3000
    networks:
      - backend_net
      - frontend_net
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: next-frontend
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:8080
    depends_on:
      - backend
    networks:
      - frontend_net
volumes:
  mysql-data:
networks:
  backend_net:
  frontend_net:
